name: Deploy .NET Feedback App to Elastic Beanstalk

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore FeedbackApp/FeedbackApp.csproj

      - name: Build application
        run: dotnet build FeedbackApp/FeedbackApp.csproj --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish FeedbackApp/FeedbackApp.csproj -c Release -o publish

      - name: Create deployment artifact
        run: |
          cd publish
          zip -r app.zip .

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: feedback-app
          environment_name: feedback-env
          region: ap-south-1
          version_label: ${{ github.sha }}-${{ github.run_number }}
          deployment_package: publish/app.zip

